#repos:
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.0.1
#    hooks:
#      - id: end-of-file-fixer
##
#  - repo: https://github.com/psf/black
#    rev: v23.12.0
#    hooks:
#      - id: black
#
#  - repo: https://github.com/PyCQA/flake8
#    rev: v7.0.0
#    hooks:
#      - id: flake8
#
#  - repo: github.com/PyCQA/isort
#    rev: v5.15.2
#    hooks:
#      - id: isort
#        args: ['--remove-unused-imports']
#
#  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
#    rev: v0.1.0
#    hooks:
#      - id: dockerfilelint