
name: Publish release to Docker Hub

# Configures this workflow to run every time a release is published.
on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/avatars-as-a-service

      - name: Set Docker tag
        id: set_tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | awk 'BEGIN{FS="/"} {print $3}')
#        run: echo ::set-output name=tag::${GITHUB_ACTOR}/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
#        run: echo ::set-output name=tag::${{ secrets.DOCKER_HUB_USERNAME }}/avatars-as-a-service:${{ github.event.release.tag_name }}
#        run: echo ::set-output name=tag::${GITHUB_ACTOR}/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}

      - name: Build Docker Image
        run: docker build -t ${{ steps.set_tag.outputs.tag }} .

      - name: Tag Docker Image
        run: docker tag ${{ steps.set_tag.outputs.tag }} ${{ secrets.DOCKER_HUB_USERNAME }}/avatars-as-a-service:${{ steps.set_tag.outputs.tag }}

      - name: Push Docker Image
        run: docker push ${{ steps.set_tag.outputs.tag }}

#      - name: Build and push Docker image
#        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{  steps.set_tag.outputs.tag }}
#          labels: ${{ steps.meta.outputs.labels }}